# GH actions.
name: Wheel-Manylinux-Nightly

on:
  push:
    branches:
      - main
      - patch-2
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *' # 6 AM UTC

jobs:
  Build:
    strategy:
      matrix:
        pkg: ['tlcpack-nightly']
        # matrix of build configs
        config:
          - cuda: 'none'
            image: 'tlcpack/package-cpu:7bfdf7e'
          - cuda: '10.2'
            image: 'tlcpack/package-cu102:7bfdf7e'
          - cuda: '11.0'
            image: 'tlcpack/package-cu110:7bfdf7e'
          - cuda: '11.1'
            image: 'tlcpack/package-cu111:7bfdf7e'
          - cuda: '11.3'
            image: 'tlcpack/package-cu113:7bfdf7e'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: TVM checkout
      run: |
        git clone https://github.com/apache/tvm tvm --recursive
    - name: Wheel-Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TLCPACK_GITHUB_TOKEN }}
      run: |
        python -m pip install pyOpenSSL --upgrade
        python -m pip install github3.py
        python wheel/wheel_upload.py --tag v0.7.dev1 tvm/python/repaired_wheels
